In [20]:
#Ve datapreprocessing'imizin son partı :)
corr_matrix = dataframe.corr()  #dataframe.corr() her bir sütun arasındaki korelasyona bakar. Biz bunu corr_matrix değişkenine eşitledik.
corr_matrix['price':]    #corr_matrix['price'] diyerek 'price' yi filtreledik fakat 1D array oluşturduk. 2D olması için sonuna : ekledik.

           year  kilometers  ...  Installments Only  price
price  0.255938   -0.077572  ...          -0.074751    1.0

[1 rows x 53 columns]

Price değişkeninin her bir sütunla yaptığın kolerasyon değerini görebilirsiniz. 1.00 tam kolerasyon , -1.00 negatif yönde tam kolerasyondur. 0.00 ise aralarında kolerasyon yoktur yani doğrular birbirine diktir. BÖLÜM 1 SONU :)